version: '3.8'

services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app  # 映射本地代码到容器内
    ports:
      - "8000:8000"  # 将容器的 8000 端口映射到本地
    environment:
      - PYTHONUNBUFFERED=1  # 防止缓冲输出，便于调试
